# module name, required
name: ${oc.env:MODULE_NAME, 'my-module'}

# base module parameters
parameters:
  # DevMode (hot Python code reload on file change)
  dev_mode: True
  detector: tracknet
  # Allows sending shutdown message to the module with the auth-key (see below)
  shutdown_auth: "shutdown"
  # enable OpenTelemetry
  telemetry:
    tracing:
      sampling_period: 100
      root_span_name: pipeline
      provider: jaeger
      provider_params:
        service_name: demo-pipeline
        endpoint: jaeger:6831

  # pipeline processing frame parameters
  frame:
    width: 1280
    height: 720
    # Add paddings to the frame before processing
  output_frame:
    codec: h264
    encoder: nvenc

  # custom drawing on frames function
  draw_func:
    module: src.module.overlay_custom
    class_name: Overlay
    #kwargs:
    # rendered_objects:
    #   peoplenet:
    #     person:
    #     face:


# pipeline definition
pipeline:
  # define pipeline's main elements
  elements:
    - element: nvinfer@attribute_model
      name: ${parameters.detector}
      model:
        format: onnx
        # local_path: /opt/savant/src/weights
        model_file: ${parameters.detector}.onnx
        input:
          # model input layer name
          layer_name: image_tensor
          # model input layer shape
          scale_factor: 0.00392156862745098 # 1/255
          shape: [3, 360, 640]
        output: 
          layer_names: [output]
          converter:
            module: src.module.tracknet_converter
            class_name: TrackNetPoseExtractor 
          # objects: # to avoid error 
          #   - class_id: 0 
          #     label: person
          attributes:
            - name: keypoints
              internal: true
        
    # custom pyfunc element
    - element: pyfunc
      module: src.module.custom_pyfunc
      class_name: BirdsEyeClipper
      kwargs:
        codec_params:
          codec: ${oc.env:CODEC, 'h264'}
